"""Real tooltip text and real suggested-value lists, extracted directly from
iw3/gui.py's own SetToolTip()/EditableComboBox(choices=...) calls (ADR-088).

Kept as a separate override layer rather than folded into schema.py's own
Field(...) definitions: schema.py's inline `tooltip=`/`choices=` stay as
short, hand-written fallbacks (used for any field not covered here, e.g. if
a new field is added before its real tooltip is back-filled), and
Field.to_dict() prefers an entry here when one exists. This mirrors the
same override-dict pattern FIELD_GROUPS already uses in schema.py, and
keeps this large, easy-to-get-subtly-wrong block of copied text isolated
in its own file rather than mixed into the field definitions themselves.

Extraction verified against the real create_parser() definitions for every
choices list here that could have a units/range mismatch (background_pop_
coverage is a 0.0-1.0 fraction, not a 0-100 percent, confirmed directly
against --background-pop-coverage's own real "0.0-1.0" help text -- so its
suggested values are given as fractions here, not the raw percent-style
numbers gui.py's tooltip text happens to describe them by). A few fields
this file's origin research flagged as possibly differing from gui.py's own
curated dropdown subset (colorspace's bt2020 entries, pix_fmt's plain
"gbrp") were independently re-confirmed as real, valid create_parser()
choices -- kept as-is; the web GUI exposing a couple more of the real CLI's
own valid values than the wx GUI's own dropdown chose to show is a
deliberate superset, not a bug.
"""

FIELD_TOOLTIPS = {
    # ---------------- General ----------------
    "resume": "What it's for: skips a file entirely if the output it would create already exists.\nHow it helps: lets you stop a big batch job partway (or have it crash/get interrupted) and restart later without wasting time redoing files you already finished.\nCon: only checks whether a file with the expected NAME exists, not whether it's actually complete or correct -- a partial/corrupted leftover file gets treated as \"done\" too.\nRecommended: on for batch folders and long jobs. Turn off only if you specifically want to force-redo everything.",
    "recursive": "What it's for: when the input is a folder, also reaches into its subfolders instead of only converting files sitting directly inside it.\nCon: if unrelated files (extras, samples, trailers) live in subfolders you didn't mean to include, they'll get converted too -- there's no per-folder include/exclude list.\nRecommended: on if you organize your movies into subfolders; off if your input folder mixes in stuff you don't want touched.",
    "skip_error": "What it's for: if a file causes an error during batch processing, note it and move on to the next file instead of stopping the whole batch. Also skips files that errored on a previous run, so they aren't retried every time.\nCon: a genuinely broken/corrupt file just gets silently skipped rather than fixed -- check the log if a file seems to be missing from your results.\nRecommended: on for large batches, so one bad file doesn't halt an overnight job. Off if you'd rather the job stop immediately so you notice a problem right away.",
    "exif_transpose": "What it's for: some cameras/phones save a photo already correctly oriented for viewing but store the actual pixel data sideways/upside-down, with a hidden tag telling viewers how to rotate it for display. This applies that rotation before conversion so the 3D effect is built for the image the way you actually see it, not the raw sideways file.\nRecommended: on (default) for virtually all real photos. Only turn off if you've confirmed your specific images have no EXIF tag or it's already wrong, since that's an unusual case.",
    "format": "What it's for: the file format used when converting still images (has no effect on video jobs, which always use your Video Format setting instead).\nValues: png = lossless, larger files, no quality loss ever -- best if you'll edit/reprocess the result later. jpeg = lossy compression, much smaller files, a small amount of quality loss (usually invisible at normal viewing sizes) -- best for sharing/storage space. webp = modern format, similar quality to jpeg at a smaller file size, but less universally supported by older software/devices.\nRecommended: png if disk space isn't a concern or you might reprocess the image later; jpeg for everyday viewing/sharing where file size matters.",

    # ---------------- Stereo Generation ----------------
    "divergence": "Also called Divergence. The master strength of the whole 3D effect -- how far things shift between the left/right eye. Higher = more dramatic depth, but more edge artifacts. Lower = subtler, cleaner. Recommended: 2.0-3.0 for most movies.",
    "method": "What it's for: which AI model/technique actually builds the second eye view from your depth map. This is one of the biggest single quality/speed decisions in the whole app.\nrow_flow_v3: fast, AI-based, a solid all-rounder -- the default.\nrow_flow_v3_sym: same family, but shifts BOTH eyes symmetrically outward from the original center image instead of keeping one eye as the unwarped original -- can look more balanced across both eyes.\nrow_flow_v2: an older generation of the row_flow model, kept for compatibility/comparison; row_flow_v3 generally looks better at the same speed.\nmlbw_l2 / mlbw_l4: a more advanced, multi-layer AI warp. l4 is the deeper/more capable version of l2 -- handles stronger 3D strength and complex scenes with fewer artifacts, at extra GPU time/memory cost.\nmlbw_l2s: a smaller/lighter version of mlbw_l2 -- faster and lower VRAM, at some quality cost versus the full mlbw_l2. Useful on lower-VRAM GPUs.\nmlbw_l2_inpaint / forward_inpaint / monobw_inpaint: any of the above families, PLUS an AI inpainting pass that fills in the hidden area behind objects instead of stretching/smearing it -- real extra time cost, but noticeably cleaner edges around foreground objects.\nforward_fill: a simple, non-AI method -- just warps pixels forward and fills gaps with a basic algorithm, no learned model involved. Fastest, but the roughest edges.\nforward_splat_fill: same non-AI forward-warp family as forward_fill, but where two pixels land on the same spot, it smoothly blends them (nearer one weighted more) instead of the nearer one fully overwriting the other -- softer, less jagged edges than forward_fill. No learned model involved, but NOT free of GPU cost: it holds several full-frame accumulator tensors in memory per batch, so its VRAM use scales up directly with Depth Batch Size (unlike the inpaint methods, which don't) and can run even a high-VRAM GPU out of memory on demanding footage at Depth Batch Size 2 or higher. Confirmed real fix if you hit an out-of-memory error here: drop Depth Batch Size to 1 and turn on Low VRAM below.\nmonobw: a simpler, lighter backward-warp method than the mlbw family -- a faster middle ground when mlbw is too slow but forward_fill's quality isn't good enough.\nRecommended: mlbw_l2_inpaint or forward_inpaint for the best quality on a real GPU; row_flow_v3_sym or mlbw_l2s if you need more speed or have limited VRAM.",
    "splat_blend_temperature": "What it's for: only matters for Method forward_splat_fill -- how sharply that method's depth-weighted blend decides which of two colliding pixels wins.\nValues: higher = sharper cutoff, closer to forward_fill's old hard-overwrite behavior (whichever pixel is nearer the camera wins almost completely); lower = smoother, more even blending between the two competing pixels.\nCon: brand new, and not yet tuned against real footage -- unlike most other numeric settings in this app, there isn't yet a body of real-world testing behind these numbers.\nRecommended: start at the default (50.0) and only adjust it if forward_splat_fill's results look wrong to you at that default.",
    "inpaint_model": "What it's for: only matters for the *_inpaint Method variants (forward_inpaint, mlbw_l2_inpaint, monobw_inpaint) -- picks which AI model fills in the hidden area behind objects that the 3D shift reveals.\nlight_inpaint_v1 is the only model included out of the box, and is what this stays on for almost everyone. Extra models only appear here if you've manually added entries to iw3/inpaint_models.yml (an advanced/optional customization, not needed for normal use).\nRecommended: leave on light_inpaint_v1 unless you've specifically installed an alternative model and know why you want it.",
    "inpaint_overlap_frames": "Overlap Pre/Post: only matters for the video inpainting methods. How many extra frames before/after each processed chunk get fed to the inpainting model purely for context, so the filled-in background doesn't flicker or change texture at chunk boundaries. Type as \"<pre> <post>\" or a single shared value.\nValues: 0 = no overlap (fastest, but a visible seam/flicker can appear where chunks join). 3 (default for both) = a small buffer that's usually enough to hide the seam.\nCon: higher values cost real extra processing time per chunk boundary, with diminishing returns past a few frames.\nRecommended: default (3 3); raise only if you actually see a flicker at chunk boundaries.",
    "mask_inner_dilation": "Inner: only matters for *_inpaint methods. Grows the \"needs filling in\" mask slightly INTO the foreground object's own edge, trimming a thin sliver off the object so the inpainted background blends in more smoothly instead of stopping at a hard line.\nCon: too high a value visibly shrinks/erodes foreground objects at their edges.\nRecommended: 0 (default); raise to 1-2 only if you see a thin, obviously wrong-colored halo clinging to the outline of foreground objects.",
    "mask_outer_dilation": "Outer: only matters for *_inpaint methods. Grows the \"needs filling in\" mask outward INTO the background, giving the inpainting model a wider area to work with around each object.\nCon: too high a value makes the model regenerate more background than it needs to, which costs a little quality/consistency versus the small sliver of real original background right at the object edge.\nRecommended: 0 (default); raise to 1-2 only if you still see leftover smearing/stretching right behind foreground objects after trying Inner dilation.",
    "inpaint_max_width": "What it's for: caps the width the inpainting model processes at, downscaling internally if the source is wider than this, to save VRAM/time on large/4K video.\nCon: lowering it can make the inpainted (filled-in) areas slightly softer/less detailed than the rest of the frame, since that step ran at a lower resolution.\nRecommended: leave blank (no limit, best quality) unless you're running out of GPU memory or need to speed up a very high-resolution job -- then try 1920 first.",
    "synthetic_view": "What it's for: decides which eye view(s) the AI actually generates from your original flat image.\nboth: generates BOTH left and right eyes fresh from the center image -- most natural, since neither eye is just the untouched original.\nright / left: keeps the original image exactly as one eye, and only generates the other -- faster (half the warping work), but can look slightly less balanced since one eye is \"real\" and the other is synthesized.\nRecommended: both, for the best-looking result. right/left mainly useful if you're very tight on processing time.",
    "convergence_mode": "What it's for: how the \"screen depth\" (the point that looks like it's exactly at the screen surface, with everything else popping toward or receding from it) is chosen.\nconstant: you set one fixed position with the value box, and it never moves for the whole video.\nsod_v1: an AI model automatically re-picks a focus point every frame, based on the most visually important subject.\nface_detect: same idea, but automatically centers on detected faces specifically, ignoring the value box.\nCon of sod_v1/face_detect: every time the convergence point moves -- even smoothed -- your eyes have to physically readjust their focus angle to keep the image comfortable to view. Real testing on this project found constant produced steadier, more comfortable results on most typical film content for exactly this reason.\nWhen sod_v1/face_detect genuinely help: a push/pull \"reveal\" shot where the camera moves from a tight close-up to a wide shot within one continuous take.\nRecommended: constant for most content -- steadier and closer to real stereographer practice. Reserve sod_v1/face_detect for content dominated by continuous push/pull reveal shots.",
    "convergence": "Also called Convergence Plane. Where the \"screen depth\" sits, from 0 (everything pops out toward you) to 1 (everything sits behind the screen). Only used directly when mode is \"constant\" -- for sod_v1 it acts as a relative offset within the detected subject's depth range. Recommended: 0.5 as a balanced starting point.",
    "convergence_smoothing": "Only affects sod_v1 / Face Detect convergence modes. Controls how quickly the automatic convergence point reacts to scene changes. Higher = smoother but slower to react. Lower = more aggressive/dynamic, reacts faster but may jitter more. 0 = no smoothing at all.",
    "ipd_offset": "Also called IPD Offset (interpupillary distance -- the gap between your own eyes). Widens or narrows the simulated eye spacing used to build the 3D effect, separate from the main 3D Strength slider.\nValues: 0 = average adult spacing (the default assumption). Positive values simulate wider-set eyes, which slightly increases the 3D pop for people with a wider-than-average IPD. Range is -10 to 20.\nCon: this is a minor personal-comfort tweak, not a real substitute for 3D Strength -- pushing it far from 0 can make the depth feel physically \"wrong\" even if stronger.\nRecommended: leave at 0 unless you specifically know your own IPD differs a lot from average and have noticed a comfort difference.",
    "stereo_width": "What it's for: only used by the row_flow_v3/row_flow_v3_sym/row_flow_v2 methods. Resizes the image to this width specifically for the eye-generation step -- separate from Depth Model's own internal resolution and separate from your final output resolution.\nCon: lowering it trades away fine detail in the warp itself for speed; the final output is still your source resolution, but the 3D shift calculation behind it was done coarser.\nRecommended: leave blank (uses the source width, best quality). Try 1920 or 1280 only if you need more speed and can accept a small quality tradeoff.",
    "depth_model": "What it's for: which AI model looks at your image/video and estimates what's near vs far. This is the foundation everything else builds on -- probably the single most important choice in the whole app.\nVDA_* (Video Depth Anything): built specifically for video -- has real memory across frames, so depth stays steady/flicker-free without needing extra smoothing settings. Best choice for movies/video by default.\nAny_V2_* / Any_V3_* / Distill_Any_*: single-image models -- often sharper/more detailed on a single photo, but have NO memory between frames, so used on video they can flicker unless you also turn on EMA smoothing and/or Object Stability.\n*_Metric variants: estimate real-world distances (meters) instead of a relative near/far scale -- a specialized option, not needed for normal stereo conversion.\nSize suffix (_S/_B/_L, small/base/large): bigger = noticeably better quality, but slower and more VRAM -- roughly proportional to size, not free.\nRecommended: a VDA_* model for video (steadiest results with the least fiddling); an Any_V3_* model for single images or when you want maximum per-frame detail on video and are willing to tune EMA/Object Stability yourself.",
    "resolution": "How much detail the depth model works with internally (its short-side resolution in pixels). Leave blank to use the model's own default (~392). Higher = finer depth detail but more VRAM/time -- roughly squares the cost as you increase it. Recommended: leave blank for most content; try 448-512 if you have VRAM to spare and want finer depth detail.",
    "limit_resolution": "Safety cap only: if your typed Depth Resolution is HIGHER than the source video's own resolution, this brings it back down to match the source instead of wasting time asking for detail that doesn't exist. It never raises a lower value up. Recommended: on.",
    "foreground_scale": "What it's for: reshapes the depth curve for the WHOLE image (-3 to 3) -- but as a redistribution, not a simple push. It's a trade-off dial, not a \"both ends get better\" dial: whichever end you push toward gains separation/detail, the OTHER end gets flattened. It cannot give a punchier foreground and a deeper background at the same time.\nValues: 0 = the depth model's own natural curve, unchanged. Positive values sharpen/spread out the FOREGROUND (more roundness/separation among near objects) while flattening the background. Negative values do the reverse -- sharpen/spread out the BACKGROUND (more sense of depth into the distance) while flattening the foreground.\nCon: pushed to an extreme in either direction, the opposite end of the scene will look noticeably flat/compressed -- this is inherent to how the curve works, not a bug.\nRecommended: 0 for natural, unexaggerated depth. Try a modest negative value (-0.5 to -1.0) if you want a more immersive/deep-feeling background; a modest positive value (+0.5 to +1.5) for a more sculpted, punchy foreground. If you want MORE separation on both ends at once instead of trading one for the other, raise 3D Strength (Divergence) instead.",
    "edge_dilation": "What it's for: smooths the depth map right at object silhouettes BEFORE the 3D shift is applied, reducing the halo/distortion artifacts that show up around foreground edges. Type as \"<x> <y>\" (Y left blank = same as X).\nImportant interaction #1: this runs BEFORE 3D Strength (Divergence) sees the depth map, and does a FIXED amount of smoothing regardless of Divergence. Raise this when you raise 3D Strength to keep the same level of edge protection (roughly: Divergence ~2.0-2.25 pairs with 2/1, Divergence ~3.0-3.5 pairs with 3/2).\nImportant interaction #2: this also runs BEFORE Depth Resolution's upscale, using a fixed-pixel-size brush on the smaller, not-yet-upscaled depth map -- re-check this any time you change Depth Resolution too.\nCon: too high smooths away real fine depth detail near edges, not just artifacts.\nRecommended: 2 1 as a starting point (X=2 horizontal, Y=1 additional vertical).",
    "depth_aa": "Smooths small jagged/staircase artifacts in the depth map using a dedicated AI model, without changing the actual depth values much. Only available for certain depth models (grayed out otherwise). Recommended: on, when available -- minor cost, generally cleaner result.",
    "depth_refine": "What it's for: cleans up noise WITHIN each depth frame using edge-preserving smoothing (won't blur across real edges the way a plain blur would). Different from Flicker Reduction, which smooths ACROSS frames over time -- this works on a single frame at a time. Cheap: no extra passes, no extra models.\nSide note some users notice: cleaner depth boundaries here can make the finished 3D effect FEEL a bit stronger/more solid even though the actual depth range doesn't change.\nRecommended: on, safe to leave on for most content. Use the Strength box to its right to control how much.",
    "depth_refine_strength": "How strong Depth Detail Refinement's cleanup is. 1.0 = the original fixed strength this feature always used. Higher = more smoothing reach (cleaner depth boundaries, but risks softening genuinely fine depth detail if pushed too far); lower = gentler, closer to doing nothing. Recommended: 1.0 as a safe starting point; try 1.25-1.5 if you want a bit more of the \"cleaner/more solid 3D\" effect this setting gives.",
    "temporal_stabilize": "Gives a single-frame depth model (like Any_V3_Mono_01) some of the same per-pixel steadiness over time that a video-native model (VDA_*) has built in. Tracks real motion (optical flow) and blends each frame's depth with the PREVIOUS frame's depth warped to where that content actually moved to, reducing a specific object's depth flickering that Flicker Reduction's overall-range smoothing can't touch. Only works on the single-frame processing path -- already active for Low VRAM, VDA streaming models, and inpaint methods (e.g. mlbw_l2_inpaint); has no effect otherwise.",
    "temporal_stabilize_strength": "How strongly to trust the motion-warped previous frame vs the fresh per-frame depth (0-1). Automatically tapers down during fast/unreliable motion regardless of this setting.",
    "foreground_pop": "What it's for: pushes ONLY the nearest pixels further toward the audience (0=off, 1=strong), leaving the rest of the scene (midground/background) completely untouched. Different from Foreground Scale, which redistributes the WHOLE depth curve and always trades foreground against background.\nCon: pushed too high, the very closest objects can pop hard enough to feel uncomfortable or clash with the frame edges (pair with Preserve Screen Border to reduce that risk).\nRecommended: 0 (off) for a restrained, professional look; 0.25-0.5 for deliberate \"poke at the audience\" moments; reserve 0.75-1.0 for a genuinely gimmicky effect.",
    "foreground_divergence": "What it's for: uses a SEPARATE 3D Strength (Divergence) value for only the nearest 15% of pixels, independent of the main 3D Strength slider above -- lets you dial the foreground up or down without touching the rest of the scene.\nValues: leave blank to disable (nearest pixels just use the same 3D Strength as everything else, the default). Set higher than your main 3D Strength for an extra-punchy foreground; lower for a gentler one.\nRecommended: leave blank unless you've specifically noticed the foreground needs its own strength independent of the rest of the scene.",
    "background_pop": "What it's for: pushes ONLY the farthest pixels further away from the audience (0=off, 1=strong), leaving the foreground/midground completely untouched. Mirror image of Foreground Pop, aimed at the opposite end of the scene.\nHow it helps: gives a deeper-feeling background without needing to redistribute the whole depth curve.\nRecommended: 0.15-0.25 for a modestly more immersive background on most content; go higher for content with a genuinely deep, expansive background you want to emphasize (landscapes, wide establishing shots).",
    "background_pop_coverage": "What it's for: how much of the scene Background Pop treats as \"background\" (0.0-1.0 fraction, e.g. 0.25 = farthest 25%; default 0.15 = farthest 15%).\nCon: larger values affect more of the scene, but push the transition line further into the midground, where a sudden change in how much a subject recedes is more likely to be noticeable as an odd \"step\" in the depth.\nRecommended: 0.15 (default) for a subtle, hard-to-notice effect; raise to 0.20-0.30 only if you want the effect to reach further into the scene and don't mind it becoming more visible.",
    "background_divergence": "What it's for: uses a SEPARATE 3D Strength (Divergence) value for only the farthest 15% of pixels, independent of the main 3D Strength slider above.\nValues: leave blank to disable (farthest pixels just use the same 3D Strength as everything else, the default). Set lower than your main 3D Strength to keep a busy/detailed background calmer and less prone to edge artifacts; set higher for a deeper-feeling background.\nRecommended: leave blank unless you've specifically noticed the background needs its own strength independent of the rest of the scene.",
    "edge_repair_strength": "Final cleanup pass on the finished 3D image (applies no matter which Stereo Method made it). Gently smooths a thin hairline right around real depth edges to reduce fringing/ghosting residue left over from the 3D warp. Cannot affect flat areas or anywhere without a depth edge. 0.0=off (default), 1.0=strongest.",
    "sharpen": "What it's for: enhances fine detail/sharpness in the FINISHED, fully-rendered 3D picture itself (after Edge Repair, if that's also on) -- different from every other sharpness-adjacent setting in this app, which all work on the DEPTH MAP instead.\nHow it avoids amplifying film grain: measures how much real local detail/edge structure is actually at each spot first and only applies the boost where that's genuinely high -- real edges and texture get sharpened, flat or grain-only areas are left close to untouched.\nRecommended: off (default) unless the finished 3D output looks a little soft to you; start at the default 0.5 Strength and raise only if you still want more.",
    "sharpen_strength": "How strong the Sharpen effect is (0.0-1.0). Higher = more pronounced detail boost at real edges/texture, but also more risk of an over-crisp/harsh look or exaggerating real compression artifacts. Recommended: 0.5 (default) as a safe starting point.",
    "ema_normalize": "What it's for (video only): smooths the depth map's overall near/far SCALE over time, so the whole image's depth intensity doesn't subtly pulse/breathe from frame to frame due to the AI model's own frame-to-frame noise. Uses the Decay Rate and Buffer settings below together.\nRecommended: on for essentially all video, paired with Scene Boundary Detection so the smoothing resets cleanly at real cuts instead of blending across them.",
    "ema_decay": "Decay Rate: how much weight past frames keep vs. the newest frame when tracking the depth-map scale. Updates every single frame, not periodically.\nValues: higher (0.9-0.99) = more resistant to momentary spikes but slower to follow a genuine intentional depth change. Lower (0.5-0.75) = reacts faster to real change, but more exposed to the AI's own per-frame noise. 0 = no smoothing at all.\nRecommended: pair with Buffer below rather than tuning alone (e.g. Decay 0.98 pairs with Buffer 120 for scenes with real smearing/bleeding artifacts). Greyed out when \"Auto EMA by Scene Length\" below is checked, since that picks its own per-scene Decay/Buffer instead.",
    "ema_buffer": "Buffer Size (in frames): how many recent frames contribute to judging the current near/far depth range, together with Decay Rate above.\nCon of too small: a single outlier frame (something briefly very close to the lens) can yank the whole normalization range around by itself, which reads as sudden smearing/swimming/bleeding in the 3D effect.\nCon of too large: slower to adapt to a genuine intentional depth change within one continuous shot.\nRecommended: 30 as a reasonable middle default; try 120 (paired with Decay 0.98) if you see smearing/bleeding artifacts. Greyed out when \"Auto EMA by Scene Length\" below is checked.",
    "ema_motion_adaptive": "What it's for: automatically eases Flicker Reduction's Decay Rate DOWN during fast motion, instead of using one fixed smoothing strength for the whole clip.\nSafety note: this can only ever REDUCE smoothing below your Decay Rate setting during fast motion, never increase it above what you set.\nRecommended: on, if your content mixes calm and fast-motion scenes (most movies do).",
    "scene_detect": "What it's for: detects real scene/shot cuts using a trained AI model (not just a simple brightness-difference trick) and resets Flicker Reduction's smoothing exactly at those points, instead of letting it bleed depth-scale information across two completely unrelated shots.\nRecommended: on for essentially all movie/TV content, especially when Flicker Reduction or Resume is also on.",
    "disable_scene_cache": "What it's for: saves detected scene cuts to disk (keyed to the source file's path, size, and modification time), so re-running the same video later -- after a crash, or while testing different 3D settings -- doesn't need to re-scan for cuts from scratch every time.\nRecommended: on. It auto-invalidates if the source file actually changes, so there's no real downside for normal use.",
    "scene_batch_auto_ema": "Automatically picks EMA Decay/Buffer per scene based on that scene's own length, using a default table -- a short scene gets a smaller Buffer so the smoothing actually finishes settling before the scene ends. Works with either Automated Scene Batch or plain Scene Boundary Detection (one of the two must be on, or Start will explain this is missing). Pick the matching table in the dropdown to its right. While this is checked, Flicker Reduction's own Decay Rate/Buffer fields above are greyed out -- their typed-in values are kept, not cleared.",
    "scene_batch_auto_ema_model": "Which Auto EMA by Scene Length table to use, matched to the Depth Model in use. 3DECKER VDA_L / 3DECKER Any_V3_Mono_01 are this project's own tables, tuned for those specific models. Nagadomi_Reference stays within the original tool author's own documented preset range. GEMINI AI / ChatGPT / Grok / Fast Action / Medium Magical / Drama Slow Paced are additional tables added for A/B comparison -- their curves came from AI suggestions and were not independently verified against nunif's own source, included as-is for comparison rather than as confirmed-correct defaults. Use \"Edit Values...\" to see or change the exact per-second numbers for whichever table is selected.",
    "preserve_screen_border": "What it's for: tapers the 3D shift down to zero right at the left/right frame edges, instead of applying full strength all the way to the border -- an automated version of the \"floating window\" technique real stereographers use, avoiding a conflict where a strongly-popped object gets cut off by the frame edge.\nCon: very slightly reduces 3D strength right at the extreme edges of the frame.\nRecommended: on for most content, especially anything with strong 3D Strength or objects that move near frame edges.",
    "stereo_format": "The final output layout. Full/Half SBS (side-by-side) and Full/Half TB (top-bottom) are the standard formats most 3D TVs and players expect -- Full keeps both eyes at full resolution (bigger file), Half squeezes both into the original frame size (smaller file, common for streaming/playback compatibility). VR180 is for VR headsets. Cross Eyed is for viewing without any equipment. Anaglyph is the red/cyan glasses look. RGB-D saves the depth data itself instead of a finished 3D image. Recommended: Half SBS for most TVs and 3D players, unless you know you need a different format.",
    "anaglyph_method": "Only used when Stereo Format is Anaglyph. The color-filtering recipe used for red/cyan glasses viewing. dubois/dubois2 give the most natural, least color-distorted result for most red/cyan glasses. gray avoids color distortion entirely but loses color in the image. Recommended: dubois2.",
    "stereo_mode_tag": "What it's for: writes the standard Matroska \"StereoMode\" property into the finished .mkv's video track, describing the 3D layout and which eye comes first, so 3D-aware players/TVs (VLC, Kodi, some smart TVs) auto-detect the correct display mode.\nOnly applies to: .mkv output, and only genuine two-eye layouts (SBS/TB/Cross Eyed) -- RGB-D and Anaglyph are skipped automatically with a printed note, not a silent no-op.\nCon: none for a normal 3D TV/player -- this is a pure metadata edit, no re-encoding.\nRecommended: on if your output goes to a 3D TV or a 3D-aware player like VLC/Kodi.",

    # ---------------- Dual-Pass Depth Blend ----------------
    "depth_blend": "Brings in a SECOND depth model and blends it into Depth Model's result, favoring the second model specifically where the image has dense fine detail (foliage, hair, close-up texture) that a single-frame model often gets wrong. Runs as 3 full passes over the clip, fully releasing each model before the next loads so both are never in GPU memory at once. Costs roughly 3x the time and real extra disk space (kept in a '<output>.depth_blend_work' folder you can delete afterward). Requires a single video file input; not compatible with Automated Scene Batch.",
    "depth_blend_model": "The SECOND depth model for Dual-Pass Depth Blend. Pick one with strengths your main Depth Model lacks -- e.g. a VDA_* model for its steadier handling of foliage/close-up detail.",
    "depth_blend_strength": "What it's for: how strongly to favor the SECOND model within the region selected below (0-1). 1.0 = fully trust the second model there; lower values blend it in more gently.\nRecommended: 1.0 to start; back off toward 0.5-0.75 if you notice any softness/ghosting at silhouettes.",
    "depth_blend_region": "What it's for: WHERE the second model gets blended in.\ndetail: wherever the image itself shows dense fine visual detail (foliage, hair, close-up texture) -- the original use case this feature was built for.\nforeground / background: a straight percentage slice of the scene BY DEPTH (nearest or farthest X%, set below), regardless of how much visual detail is actually there.\nRecommended: detail for the original foliage/hair use case; foreground/background only if you specifically want the second model's characteristics applied to a whole depth range instead.",
    "depth_blend_region_percent": "For \"foreground\"/\"background\" region only (ignored for \"detail\"): what percent of the scene, by depth, to blend the second model into -- e.g. 25 = nearest (or farthest) 25% of the scene.\nRecommended: 25 as a starting point; keep it modest unless you have a specific reason to cover more of the scene.",

    # ---------------- Video Filter ----------------
    "start_time": "Only process the video from this timestamp onward, instead of from the beginning. Useful for testing settings on a specific scene, or trimming unwanted intro footage.",
    "end_time": "Stop processing at this timestamp instead of the end of the video.",
    "vf": "Advanced: a raw ffmpeg video filter string applied to the source before 3D conversion. Leave blank unless you specifically need this -- most common needs (crop, rotate, pad, resize) already have their own simpler controls.",
    "rotate_left": "Rotate the source video 90 degrees counterclockwise before 3D conversion, e.g. for footage shot sideways on a phone.",
    "rotate_right": "Rotate the source video 90 degrees clockwise before 3D conversion, e.g. for footage shot sideways on a phone.",
    "autocrop": "Automatically detects and removes black bars or plain/flat borders before 3D conversion (so they don't waste depth detail or get distorted). _TB variants only crop top/bottom bars; the non-TB variants crop on all sides.",
    "pad": "How much padding to add, as a ratio of frame size (only applies if Padding Mode is also set). Con: larger values waste more of the frame on empty border instead of picture content. Recommended: start small (0.01-0.05).",
    "pad_mode": "What it's for: adds solid padding/border area around the frame before the 3D shift is applied, giving objects near the edges more room to shift into without hitting the frame boundary.\ntblr = all sides (default). tb = top and bottom only. lr = left and right only. top = top only. 16:9 = pads to a 16:9 aspect ratio specifically.\nRecommended: leave at default unless you're seeing objects clipped by the frame edge even with Preserve Screen Border on.",
    "max_output_width": "What it's for: caps the FINAL PACKED FRAME's resolution (the whole SBS/TB image, after both eyes are already combined -- not a per-eye limit). Leave blank to keep the source's native size, uncapped.\nImportant: Full SBS builds a canvas DOUBLE your source's width. If you cap this at your target delivery resolution with Keep Aspect Ratio off, Full SBS can end up pixel-for-pixel identical to Half SBS. For true Full SBS, set this to double your target width/height, or leave it blank.\nRecommended: match this to whichever Stereo Format you picked so the numbers actually make sense together.",
    "max_output_height": "See Max Output Width's tooltip -- the two work together as one output size cap.",
    "keep_aspect_ratio": "What it's for: when Output Size is capped, proportionally shrinks to fit inside it instead of crushing width and height independently to exactly match the cap.\nRecommended: turn on if you're not carefully matching the size cap to double/single width for your Stereo Format choice, so an undersized cap shrinks proportionally instead of distorting the image.",
    "preserve_dowi": "What it's for: detects Dolby Vision RPU and/or HDR10+ dynamic metadata on the source and re-attaches it to the finished 3D video, so the HDR grading survives conversion instead of being silently dropped.\nRequires: HEVC output and MKVToolNix installed for MKV output.\nRecommended: on for any Dolby Vision or HDR10+ source you want to keep looking correct on an HDR display after conversion.",
    "hdr_to_sdr": "Properly tone-maps a PQ/HDR10/HDR10+ or HLG source down to normal SDR brightness before conversion, while keeping 10-bit color precision. Automatically does nothing if the source isn't actually HDR. Turns off Preserve Dolby Vision, since the two are contradictory. Recommended: on for HDR sources being watched on a non-HDR display.",
    "auto_resume": "Lets a long conversion pick back up exactly where it left off if it's interrupted (crash, power loss, or clicking Cancel), instead of starting over from the beginning. A normal, uninterrupted run has zero seams, identical to not using this option at all -- a seam only appears at the exact point an interruption actually happened. Recommended: on for any long/overnight conversion.",
    "denoise": "What it's for: applies temporal (across-frame) denoising to the SOURCE before depth estimation even sees it. Reduces film grain/sensor noise that can otherwise confuse the depth model into reading noise as fake texture/detail.\nCon: real extra time up front (a full separate pass over the whole video), and always risks softening some genuine fine detail along with the grain.\nRecommended: on for visibly grainy/old sources; off for clean, modern digital sources.",
    "preview": "What it's for: quickly renders just the first 60 seconds at 1fps and low resolution instead of a full conversion, so you can check your settings look right before committing to a full-length run.\nRecommended: on whenever you're testing new settings on a file for the first time; off for your actual final conversion run.",
    "upgrade_pix_fmt": "Gives the internal depth/3D math more color precision to work with, reducing banding (visible color \"steps\" in skies/shadows) -- it doesn't add detail that wasn't in the source. Recommended: 10 for most sources, a real, visible improvement over 8-bit with low cost. 12 adds little you can actually see on a normal screen, for extra file size and slower encoding.",
    "metadata": "What it's for: encodes your current settings (depth model, 3D strength, convergence, edge options, etc.) into the output filename as short abbreviated tags, and also writes them into the video's own comment metadata.\nHow it helps: lets you tell which settings made which file just by looking at the filename later, and lets Resume correctly match an in-progress job back up after an interruption.\nCon: filenames get noticeably longer and less readable at a glance.\nRecommended: on, unless you strongly prefer short/clean filenames.",
    "scene_batch": "Fully automated whole-movie pipeline: removes letterbox bars once, detects scene cuts once, splits into per-scene clips with exact keyframe-accurate boundaries, converts each scene independently (a true fresh start per scene), then joins the results back into one seamless video and reattaches the original audio. Input must be a single video file, not a folder.",
    "scene_batch_crop": "Optional, for Automated Scene Batch. Explicit crop as WxH or WxH:X:Y. Leave blank to auto-detect letterbox bars once from the whole movie.",
    "scene_settings": "Optional, for Automated Scene Batch. JSON file giving per-scene setting overrides (e.g. a different Divergence for different stretches of the movie). Leave blank to use the same settings for every scene.",
    "scene_batch_variant": "Optional, for Automated Scene Batch. Reuses the shared, already-done work from a prior run of the SAME movie (RPU, crop+keyframe pass, split scene clips) but writes its own converted scenes and final output under this name, so trying different settings here never overwrites an earlier attempt. Output becomes <name>_<variant>.<ext>.",

    # ---------------- Video Decoding ----------------
    "hwaccel": "Use your GPU to decode (read) the source video instead of the CPU -- much faster, and frees up CPU time for other work, with no quality difference. Leave blank to always use CPU decoding. Recommended: select your GPU's option (e.g. cuda for NVIDIA) if available.",
    "disable_software_fallback": "Use software (CPU) decoder if hardware acceleration fails or is unsupported for a particular file, instead of stopping with an error. Recommended: leave off (fallback enabled) for reliability.",

    # ---------------- Video Encoding ----------------
    "video_format": "The output container/file type. mp4 is the most universally compatible. mkv supports more advanced features (like Dolby Vision/HDR10+ metadata and lossless codecs). avi is mainly for the lossless utvideo codec. Recommended: mkv if you need HDR/Dolby Vision or lossless output, mp4 otherwise.",
    "video_codec": "The compression format used to encode the output video. libx264/libx265 (CPU-based, h264/HEVC) give the best quality-per-file-size and work everywhere. h264_nvenc/hevc_nvenc use your NVIDIA GPU's hardware encoder -- much faster, slightly lower quality-per-file-size. utvideo/ffv1 are lossless (huge files, no quality loss) for archival/further editing. Recommended: libx265 for best quality, hevc_nvenc if encoding speed matters and you have an NVIDIA GPU.",
    "max_fps": "Caps the output frame rate. If the source is already at or below this, nothing changes. Lowering it reduces processing time roughly proportionally, at the cost of less smooth motion. Recommended: leave high (e.g. 1000) to just keep the source's own frame rate.",
    "pix_fmt": "The color sampling/precision the encoder stores internally. yuv420p (8-bit) is the most compatible default. yuv420p10le adds precision that reduces banding. yuv444p/rgb24/gbrp* avoid color-detail loss around sharp red/edge areas, at a larger file size. Recommended: yuv420p10le for most uses.",
    "colorspace": "How color values are tagged/interpreted (affects color accuracy on playback, not detail). \"auto\" matches the source's own colorspace and is correct for virtually all sources. Only change this if you know your source's colorspace is mistagged.",
    "crf": "Constant Rate Factor: the main quality/file-size dial for most codecs. Lower number = higher quality and bigger file; higher number = smaller file and lower quality. Recommended: 15-18 for near-lossless/archival quality, 20-23 for a good everyday balance.",
    "video_bitrate": "Only used by libopenh264, which doesn't support CRF. Sets a fixed data rate for the video (M = megabits/second) -- higher = better quality and bigger file. Recommended: 8M-16M for 1080p, higher for 4K.",
    "preset": "How hard the encoder works to compress efficiently. Slower presets (slow/slower/veryslow) give a smaller file at the same quality, but take longer to encode. Faster presets (fast/veryfast/ultrafast) encode quicker but produce a larger file for the same quality. Recommended: medium-slow for a good balance; veryfast if encoding time matters more than file size.",
    "tune": "For libx264/libx265: nudges the encoder's choices for a specific kind of content -- e.g. \"grain\" preserves film grain/noise better, \"animation\" suits flat-color cartoon content. Leave blank unless your source clearly matches one of these categories.\nFor hevc_nvenc/h264_nvenc: chooses the GPU encoder's quality/speed tradeoff. \"hq\" = high quality (good default). \"uhq\" (HEVC only, recent NVIDIA GPUs) = even higher quality than hq at a modest speed cost. \"lossless\" = no quality loss, very large file. \"ll\"/\"ull\" are for live-streaming, not useful for a normal conversion. \"fastdecode\"/\"zerolatency\" can also be typed here directly (space/comma separated with other values) -- fastdecode makes the file easier to decode on weak playback devices at a small compression-efficiency cost.",
    "profile_level": "A technical compatibility limit (resolution/bitrate ceiling) some older TVs/players check before they'll play a file. Recommended: \"auto\" -- only set this manually if a specific playback device of yours refuses to play the output.",

    # ---------------- Processor ----------------
    "device": "Which GPU (or CPU) does the AI processing. \"All CUDA Device\" splits work across every GPU you have for faster batch processing. CPU works without a GPU but is dramatically slower -- only use it if you have no compatible graphics card.",
    "fp16": "Use FP16 (fast) -- runs the AI math at lower numeric precision, which is significantly faster and uses less VRAM on modern GPUs, with no visible quality cost in virtually all cases. Recommended: on.",
    "low_vram": "Trades speed for lower memory use, by processing in a way that needs less VRAM at once. Only turn this on if you're actually running out of memory -- it will make things slower.\nConfirmed real fix for Method forward_splat_fill's out-of-memory crashes on demanding footage, even when Depth Batch Size is already set to 1 -- turn this on if that method OOMs for you.",
    "compile": "Enable model compiling: optimizes the AI model before running, trading a slower startup (the first run after changing settings has to compile) for faster processing afterward. Worth it for long videos; not worth it for a single quick image or short clip. Requires extra setup (see this project's torch_compile docs) to actually take effect.",
    "batch_size": "Video Only. How many frames are sent to the depth model at once. Higher = faster overall but uses more VRAM. Lower it if you run out of memory; raise it if you have VRAM to spare and want faster processing. Ignored when Low VRAM is on.",
    "max_workers": "Video Only. How many CPU threads handle the stereo/inpainting step and frame I/O in parallel. Higher can speed things up on a multi-core CPU, but uses more RAM/VRAM. Lower it if you run into memory issues or system slowdowns while converting.",
    "tta": "Use flip augmentation to improve depth quality (slow). Runs the depth model on both the normal and mirrored image/video and blends the result, often a little cleaner/more accurate, at roughly double the processing time. Recommended: off for long videos (Flicker Reduction already covers similar ground there, for free) -- worth trying for a single hero image or a short clip.",
    "cuda_stream": "Use per-thread CUDA Stream (experimental: fast or slow or crash). Lets multiple worker threads share the GPU more aggressively. May speed things up, may do nothing, may occasionally cause instability -- try it and turn it back off if you see crashes.",
    "pause_frees_vram": "What: when you click Suspend, also move every loaded model off the GPU and actually release that VRAM back to Windows, instead of just pausing while everything stays loaded. Resume moves them all back before continuing.\nCons: Resume is no longer instant -- reloading takes a few seconds (longer if torch.compile is on). No effect with multi-GPU (\"All CUDA Device\").\nRecommended: off, unless you specifically need the GPU free for something else during a long pause.",
    "waifu2x_upscale": "What it's for (single video and Dual-Pass Depth Blend jobs only): once this job's finished output is fully written, automatically runs it through waifu2x (a separate, dedicated AI upscaler bundled with this app) as one extra step.\nHow it's safe: saved to a separate '_w2x' file -- the original conversion output is always left untouched, even if the upscale step itself fails.\nRecommended: on if you specifically want a higher-resolution final delivery file; off if your source resolution is already your target.",
    "waifu2x_upscale_target": "What it's for: only takes effect on a packed 3D stereo video output. \"auto\" (default) leaves the plain whole-frame upscale unchanged. \"4k\"/\"8k\" instead switch to a stereo-aware upscale: each eye is split out and upscaled separately (avoiding blurring pixels across the seam between eyes), with flicker-reducing smoothing, then recombined at the requested final width.\nCon: several extra full passes over the video, so real processing time is meaningfully longer.\nRecommended: auto unless you specifically need a 4K/8K delivery file from a 3D stereo source.",
    "rife_interpolate": "What it's for (single video and Dual-Pass Depth Blend jobs only): once this job's finished output is fully written, runs it through RIFE (a separate AI frame-interpolation model) as one extra step, generating new in-between frames for smoother-looking motion.\nHow it's safe: saved to a separate '_rife' file -- the original conversion output is always left untouched.\nCannot be combined with Preserve Dolby Vision: there's no way to assign correct DV/HDR10+ metadata to RIFE's synthetic in-between frames.\nRecommended: on if your source is naturally low frame rate (e.g. 24fps film) and you want smoother motion; off if you need Dolby Vision preserved.",
    "rife_model": "Which RIFE model quality tier to use. rife_425: the recommended full model -- better motion accuracy on complex/fast motion, at a higher compute cost. rife_425_lite: a lower-compute-cost variant, trades a little accuracy for speed. Weights download automatically the first time you use a given tier. Recommended: rife_425 unless interpolation time is a real bottleneck.",
    "rife_multiplier": "What it's for: how many new frames RIFE inserts. 2x/3x/4x inserts 1/2/3 evenly-spaced new frames between every pair of real frames, multiplying the frame rate by that exact amount.\nRecommended: 2x for most uses. Mutually exclusive with RIFE Target FPS.",
    "rife_target_fps": "What it's for: the exact output frame rate to interpolate to, used instead of a simple multiplier, even when it isn't a clean multiple of the source.\nValues: any number higher than your source video's own frame rate.\nRecommended: 60 for standard smooth-motion displays, or match your target display/editing timeline's exact refresh rate.",
}

# Suggested/preset values for combo_editable and select fields -- an
# override, not a hard restriction: combo_editable fields still accept any
# typed value, this just changes what's offered in the dropdown/datalist.
# Units independently re-verified against each field's real create_parser()
# definition before inclusion (see this file's own module docstring).
FIELD_CHOICES = {
    "format": ["png", "jpeg", "webp"],
    "splat_blend_temperature": ["10.0", "25.0", "50.0", "75.0", "85.0"],
    "convergence": ["0.0", "0.25", "0.5", "1.0"],
    "convergence_smoothing": ["0.95", "0.9", "0.75", "0.5", "0.25", "0"],
    "stereo_width": ["1920", "1280", "640"],
    "resolution": ["512"],
    "foreground_scale": ["-3", "-2", "-1", "0", "1", "2", "3"],
    "depth_refine_strength": ["1.5", "1.25", "1.0", "0.75", "0.5", "0.25"],
    "temporal_stabilize_strength": ["0.9", "0.7", "0.5", "0.3"],
    "foreground_pop": ["0.0", "0.25", "0.5", "0.75", "1.0"],
    "foreground_divergence": ["2.0", "2.5", "3.0", "3.5", "4.0"],
    "background_pop": ["0.0", "0.25", "0.5", "0.75", "1.0"],
    # Real unit is a 0.0-1.0 fraction (confirmed directly against
    # --background-pop-coverage's own create_parser() help text), NOT the
    # 0-100-style percent numbers the wx GUI's tooltip prose describes them
    # by -- given here as fractions to match the field's real value_type.
    "background_pop_coverage": ["0.15", "0.20", "0.25", "0.30", "0.40"],
    "background_divergence": ["2.0", "2.5", "3.0", "3.5", "4.0"],
    "edge_repair_strength": ["0.0", "0.25", "0.5", "0.75", "1.0"],
    "sharpen_strength": ["0.25", "0.5", "0.75", "1.0"],
    "ema_decay": ["0.99", "0.95", "0.9", "0.75", "0.5", "0"],
    "ema_buffer": ["150", "60", "30", "1"],
    "pad": ["0.01", "0.05", "0.5", "1"],
    "crf": [str(n) for n in range(16, 28)],
    "video_bitrate": ["160M", "50M", "16M", "12M", "8M", "4M"],
    "profile_level": ["auto", "3.0", "3.1", "3.2", "4.0", "4.1", "4.2",
                       "5.0", "5.1", "5.2", "6.0", "6.1", "6.2", "8.5"],
    "batch_size": ["64", "32", "16", "14", "13", "12", "11", "10", "9", "8", "4", "3", "2", "1"],
    "max_workers": ["16", "14", "12", "11", "9", "8", "7", "6", "5", "4", "3", "2", "1", "0"],
}
